services:

  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: scottkang123
      POSTGRES_PASSWORD: scottkang123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-net
    restart: unless-stopped

  keycloak:
    container_name: keycloak-fa
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - microservices-net
    command:
      - "start-dev"

#  mongo:
#    container_name: mongo
#    image: mongo
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo:/data
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=scottkang123
#      - MONGO_INITDB_ROOT_PASSWORD=scottkang123
#    networks:
#      - microservices-net
#
#  mongo-express:
#    container_name: mongo_express
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=scottkang123
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=scottkang123
#      - ME_CONFIG_MONGODB_SERVER=mongo
#    networks:
#      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
  keycloak:
    driver: local